name: Daily Price Scraper

on:
  schedule:
    - cron: '0 6 * * *' # Her gün TSİ 09:00'da otomatik çalışır
  workflow_dispatch: # GitHub panelinden elle çalıştır butonu

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install curl_cffi psycopg2-binary playwright
          playwright install chromium
          playwright install-deps

      - name: Run Scraper Script
        run: python scraper.py
